apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "arango-create-database.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ template "arango-create-database.fullname" . }}
      labels:
        app: {{ template "arango-create-database.fullname" . }}
    spec:
      containers:
      - name: {{ template "arango-create-database.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args: [
          "--log-level",
          "info",
          {{- if eq .Values.endpoint "https" }}
            "--is-secure",
          {{- end }}
          "create-database",
          "--admin-user",
          "{{ .Values.admin.user }}",
          "--admin-password",
          "{{ .Values.admin.password }}",
          {{ range .Values.database.names }}
          "--database",
          {{ . | quote }},
          {{ end }}
          "--user",
          "{{ .Values.database.user }}",
          "--password",
          "{{ .Values.database.password}}",
          "--grant",
          "{{ .Values.database.grant }}"
        ]
      restartPolicy: Never
